import time
import RPi.GPIO as GPIO
GPIO.setmode(GPIO.BOARD)
GPIO.setwarnings(False)

count=0

#SENSOR PINS
TRIG = 7
ECHOF = 8
ECHOFL = 10
ECHOFR = 11
ECHOL = 12
ECHOR = 13
ECHOBL = 15
ECHOBR = 19
ECHOB =  21

#SETUP SENSOR ARRAY
sensors = [ECHOFL, ECHOL, ECHOBL, ECHOB, ECHOBR, ECHOF, ECHOFR, ECHOR]
sensors_len = len(sensors)
distances = []

#SENSOR SETUP
GPIO.setup(ECHOF, GPIO.IN)
GPIO.setup(ECHOFL, GPIO.IN)
GPIO.setup(ECHOFR, GPIO.IN)
GPIO.setup(ECHOL, GPIO.IN)
GPIO.setup(ECHOR, GPIO.IN)
GPIO.setup(ECHOBL, GPIO.IN)
GPIO.setup(ECHOBR, GPIO.IN)
GPIO.setup(ECHOB, GPIO.IN)
GPIO.setup(TRIG, GPIO.OUT)

#MOTOR PINS
LEFTENABLE = 33
RIGHTENABLE = 32

LEFTINPUT1 = 31
LEFTINPUT2 = 35
RIGHTINPUT3 = 36
RIGHTINPUT4 = 37

#MOTOR SETUP
GPIO.setup(LEFTENABLE, GPIO.OUT)
GPIO.setup(RIGHTENABLE, GPIO.OUT)
GPIO.setup(LEFTINPUT1, GPIO.OUT)
GPIO.setup(LEFTINPUT2, GPIO.OUT)
GPIO.setup(RIGHTINPUT3, GPIO.OUT)
GPIO.setup(RIGHTINPUT4, GPIO.OUT)

#PWM INITIALISE
LPWM = GPIO.PWM(LEFTENABLE, 200)
RPWM = GPIO.PWM(RIGHTENABLE, 200)
LPWM.start(0)
RPWM.start(0)

time.sleep(0.5)

#DEFINE FUNCTION
def FORWARD(LEFT, RIGHT, DURATION):
    print("Left motor: ", LEFT, "Right motor: ", RIGHT)
    GPIO.output(LEFTINPUT1, 0)
    GPIO.output(LEFTINPUT2, 1)
    GPIO.output(RIGHTINPUT3, 0)
    GPIO.output(RIGHTINPUT4,1)
    LPWM.ChangeDutyCycle(LEFT)
    RPWM.ChangeDutyCycle(RIGHT)
    time.sleep(DURATION)

FORWARD(20, 29, 5)
GPIO.cleanup()


